name: Experiment
on: [push]
jobs:
  first_job:
    name: My Job Name
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: GolangCI-Lint experiment
        uses: docker://matousdz/golangci-lint-action:v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
